#!/usr/bin/env bash
# =============================================================================
# claude-quality-worker config for: __REPO_NAME__
# Generated by install.sh — edit freely to customize
# =============================================================================

# Virtual environment activate script (leave empty to skip)
VENV_PATH="__VENV_PATH__"

# Git branch prefix for quality branches
# Branches: quality/lint/YYYY-MM-DD, quality/types/YYYY-MM-DD, etc.
QUALITY_BRANCH_PREFIX="__BRANCH_PREFIX__"

# How many days to keep log files
LOG_RETENTION_DAYS=30

# --- Quality tool commands ---
# __DETECTED_NOTE__

# Lint check command
LINT_COMMAND="__LINT_COMMAND__"

# Lint auto-fix command
LINT_FIX_COMMAND="__LINT_FIX_COMMAND__"

# Type check command
TYPECHECK_COMMAND="__TYPECHECK_COMMAND__"

# Test command
TEST_COMMAND="__TEST_COMMAND__"

# --- Scope ---

# Source directories to scan (space-separated)
SOURCE_DIRS="__SOURCE_DIRS__"

# Documentation files/directories to track (space-separated)
DOC_FILES="__DOC_FILES__"

# Max files per baseline batch (controls Claude's context budget)
DEFAULT_BATCH_SIZE=15
